name: sht3x
description: Driver for Sensirion SHT30/SHT31/SHT35 digital temperature and humidity sensor
version: 1.0.0
groups:
  - temperature
  - humidity
code_owners: Pl0uf-tlt
depends:
  - driver
  - common_sensirion_sensor
thread_safe: yes
targets:
  - esp32h2
license: BSD-3
copyrights:
  - name: Pl0uf-tlt
    year: 2024
