name: sht3x
description: Driver for Sensirion SHT30/SHT31/SHT35 digital temperature and humidity sensor
version: 1.1.0
groups:
  - temperature
  - humidity
code_owners: Pl0uf-tlt
depends:
  - log
  - esp_idf_lib_helpers
thread_safe: yes
targets:
  - esp32
  - esp32s2
  - esp32c3
license: BSD-3
copyrights:
  - name: UncleRus
    year: 2016
  - name: gschorcht
    year: 2017
  - name: Pl0uf-tlt
    year: 2024
